title: MotionIO
date: 2014
tag: web, processing 
content: |
  - MotionIO is an interactive audio-visual experience for multiple people, intended for installation in a public area. Using open web technologies, participants use the motion of their mobile phones to control and interact with an organic generative system and each other. In this shared virtual environment, using a mobile device in public is transformed from a private act into a social one, creating a playful collaborative space where unique combinations of sound and light can form. 
  - ff


  