title: MotionIO
date: 2014
tag: web, processing 
content: |
  <ul>
  <li><img src="https://farm6.staticflickr.com/5200/14063845389_f79caa3510_b.jpg" alt="MotionIO: One Great Image"></li>
  <li>MotionIO is an interactive audio-visual experience for multiple people, intended for installation in a public area. Using open web technologies, participants use the motion of their mobile phones to control and interact with an organic generative system and each other. In this shared virtual environment, using a mobile device in public is transformed from a private act into a social one, creating a playful collaborative space where unique combinations of sound and light can form. </li>
  <li class="hasVid"><div class= "vimeo-container"> <iframe src="//player.vimeo.com/video/93030550?title=0&amp;byline=0&amp;portrait=0" width="1280" height="720" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div></li>
  <li>This project was developed from January – May 2014 as my final degree honours project. It uses WebSockets to stream real time device accelerometer/gyroscope data from the the HTML5 Device Orientation API to a Processing application. Users can interact with a flocking system, and MIDI data is generated from their input to control synthesisers. The system uses a dedicated wi-fi router with a local DNS redirect to make the experience of joining and using it as simple as possible.  </li>
  
  
  <li><img src="https://farm6.staticflickr.com/5537/14063836058_5a91d05c09_b.jpg" alt="People using MotionIO at the 2014 DJCAD Degree Show opening night">    </li>
  <li><img src="https://farm3.staticflickr.com/2925/14063845439_896c0273f7_b.jpg" alt="People using MotionIO at the 2014 DJCAD Degree Show opening night">    </li>
  <li>
  <img src="https://farm3.staticflickr.com/2936/14064622999_e0734fa666_b.jpg" alt="The UI seen on the mobile device">
  </li>
  
  <li>
  <img src="https://farm6.staticflickr.com/5485/14064623079_77a08ddcc2_b.jpg" alt="Screenshot of three users interacting, with settings UI">
  </li>
  
  <li>
  <img src="https://farm6.staticflickr.com/5234/14064693187_57e97688d0_b.jpg" alt="Three users interacting, with no UI">
  </li>
  
  <li>
  <img src="https://farm3.staticflickr.com/2919/14064611878_9867c12934_b.jpg" alt="An earlier iteration of a single user.">
  </li>
  <li>
  <p>
  You can see <a href="https://velvetkevorkian.github.io/honoursPres" target="blank">the slides I made for my final viva here</a>, which includes some of the inspiration and design iterations the project went through. If you're interested displaying this project, or in using the technology behind it, please get in touch. 
  </p>
  </li>
  
  
  
  
  </ul>


  