title: ASCII Art for Brackets
date: 2014
description: A Brackets plugin for creating ASCII art
tag: Brackets, JavaScript 
content: |
  - ![Screenshot of the plugin in action with a dark Brackets theme] (https://farm3.staticflickr.com/2936/14066187607_8f29cbd6e2_b.jpg)
  - A Brackets plugin implementing Figlet.js for using ASCII Art fonts in code. 
  - ![Screenshot of the plugin in action with a light Brackets theme](https://farm6.staticflickr.com/5521/14252766175_81dc9754ba_b.jpg)