title: Telefónica Sustainability Report
date: 2013
tag: web, responsive 
content: |
  - ![Report homepage](https://farm3.staticflickr.com/2871/11998512643_a60dd1862b_b.jpg)
  - ![Blueprint homepage](https://farm4.staticflickr.com/3770/11998220875_931a74c028_b.jpg)
  - ![CEO's Message](https://farm8.staticflickr.com/7331/11998512873_d8b83eb176_b.jpg)
  - ![40 Commitments ](https://farm3.staticflickr.com/2853/11998578274_4f9405c929_b.jpg)
  - ![Content page with content on left](https://farm4.staticflickr.com/3722/11998218225_6f1ed0d0e5_b.jpg)
  - ![Content page with content on right](https://farm4.staticflickr.com/3794/11998509903_3d2398a67f_b.jpg)
  - ![Site plan showing proposed templates](https://farm6.staticflickr.com/5539/11998508523_f4e0fb612a_b.jpg)
  - ![Template wireframe example](https://farm8.staticflickr.com/7328/11998571584_181142384d_b.jpg)
  
  - I spent three months over summer 2013 working on this project for Telefónica UK (better known as O2). As part of their sustainability commitments, the team at Telefónica decided to use this project as an opportunity to put their money