title: Telefónica Sustainability Report
date: 2013
tag: web, responsive 
content: |
  - I spent three months over summer 2013 working on this project for Telefónica UK (better known as O2). As part of their sustainability commitments, the team at Telefónica decided to use this project as an opportunity to put their money