title: Processing Showreel
date: 2011
description: A collection of Processing work, including generative systems and simple fractals.
tag: Processing
content: |
    <ul>
    <li><div class= "vimeo-container"><iframe src="//player.vimeo.com/video/19745219?title=0&amp;byline=0&amp;portrait=0" width="1280" height="720" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div></li>
    <li>I put together this video compilation of Processing work when I was applying for university in early 2011: it formed the backbone of the effort which got me in to study at <a href="http://www.dundee.ac.uk/djcad/)">DJCAD in Dundee</a>. It shows a lot of the ideas that continue to interest me.</li>
    </ul>